backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: hackerstolz/hackathon-frontend

# media_folder: "" # Media files will be stored in the repo under images/uploads
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
logo_url: "https://www.hackerstolz.de/wp-content/uploads/2015/07/hackerstolz-logo.svg"

collections:
  - name: "hackathon" # Used in routes
    label: "Hackathon" # Used in the UI
    folder: "content/hackathons" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: json
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{title}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "URL Name", name: "urlName", widget: "string", pattern: ['[a-zA-Z0-9_-]*', "URL safe: only characters and numbers"], hint: "A unique(!) URL safe string used in the URL to navigate to this Hackathon"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Default", name: "default", widget: "boolean", default: false, hint: "Hackathon shown if none specified in URL"}
      - {label: "Active", name: "active", widget: "boolean", default: false, hint: "Visible on website"}
      - {label: "From", name: "from", widget: "datetime", format: "X"}
      - {label: "To", name: "to", widget: "datetime", format: "X"}
      - {label: "Duration", name: "duration", widget: "number", valueType: "int", hint: "Hackduration in Hours"}
      - {label: "Event Page active", name: "eventPageActive", widget: "boolean", default: false, required: false, hint: "Event Page accessible"}
      - {label: "Contact EMail", name: "contactEmail", widget: "string", pattern: ['.*@.*\.', "Please provide a valid Email-Address"]}
      - {label: "Twitter Handle", name: "twitter", widget: "string"}
      - {label: "Hashtag", name: "hashtag", widget: "string"}
      - label: Ticketshop Link
        name: linkTicketshop
        widget: "relation"
        collection: "link"
        required: false
        searchFields: ["id", "name"]
        valueField: "id"
        displayFields: ["name"]
      - label: Community Link
        name: linkCommunity
        widget: "relation"
        collection: "link"
        required: false
        searchFields: ["id", "name"]
        valueField: "id"
        displayFields: ["name"]
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"
        required: false
        hint: "Preview image, e.g. shown in browser"
        media_library:
          config:
            max_file_size: 250000 # 250kb       
      - label: Meta Descriptions
        name: descriptions
        widget: list
        required: false
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Description, name: description, widget: text}
      - label: Awards
        name: awards
        widget: list
        required: false
        fields:
          - label: Award
            name: award
            widget: "relation"
            collection: "award"
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
      - label: FAQs
        name: faqs
        widget: list
        required: false
        fields:
          - label: FAQ
            name: faq
            widget: "relation"
            collection: "faq"
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
  - name: "challenge"
    label: "Challenge"
    folder: "content/challenges"
    create: true
    format: json
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string"}
      - label: Titles
        name: titles
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Title, name: title, widget: string}
      - label: Hackathon
        name: hackathon
        widget: "relation"
        collection: "hackathon"
        searchFields: ["id", "title"]
        valueField: "id"
        displayFields: ["title"]
      - label: Image
        name: image
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 512000 # 500kb
      - label: Descriptions
        name: descriptions
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Description, name: description, widget: markdown}
      - label: Award
        name: award
        widget: "relation"
        required: false
        collection: "award"
        searchFields: ["id", "name"]
        valueField: "id"
        displayFields: ["name"]
      - label: Type
        name: type
        widget: "relation"
        required: false
        collection: "type"
        searchFields: ["id", "title"]
        valueField: "id"
        displayFields: ["title"]
      - label: Category
        name: category
        widget: "relation"
        collection: "category"
        required: false
        searchFields: ["id", "name"]
        valueField: "id"
        displayFields: ["name"]
      - label: Author
        name: author
        widget: list
        hint: "Name the author or provider of the challenge"
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: author, name: author, widget: string}
  - name: "link"
    label: "Link"
    folder: "content/links"
    create: true
    format: json
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: URL, name: url, widget: string}  
      - label: Titles
        name: titles
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Title, name: title, widget: string}            
  - name: "type"
    label: "Challenge Type"
    folder: "content/types"
    create: true
    format: json
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{title}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Title", name: "title", widget: "string"} 
      - label: Descriptions
        name: descriptions
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Description, name: description, widget: markdown}
  - name: "category"
    label: "Category"
    folder: "content/categories"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string", hint: "Used in Admin UI only"}
      - label: Titles
        name: titles
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Title, name: title, widget: string}  
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 256000 # 250kb
      - label: Award
        name: award
        widget: "relation"
        required: false
        collection: "award"
        searchFields: ["id", "name"]
        valueField: "id"
        displayFields: ["name"]
      - label: Descriptions
        name: descriptions
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Description, name: description, widget: markdown}
  - name: "award"
    label: "Award"
    folder: "content/awards"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string", hint: "Used in Admin UI only"}
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 256000 # 250kb
      - label: Titles
        name: titles
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
      - label: Prize
        name: prize
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Prize, name: prize, widget: string}
      - label: Descriptions
        name: descriptions
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Description, name: description, widget: markdown, hint: "Please describe the award."}  
      - label: Criteria
        name: criteria
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Criteria, name: criteria, widget: markdown, hint: "Please describe the criteria which apply for this awards."}     
  - name: "person"
    label: "Person"
    folder: "content/persons"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Salutation", name: "salutation", widget: select, options: ["W", "M"]}
      - label: Image
        name: image
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 512000 # 500kb
      - label: Roles
        name: roles
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "Used in Admin UI only??? Obsolete?"}  
          - label: Hackathon
            name: hackathon
            widget: "relation"
            collection: "hackathon"
            searchFields: ["id", "title"]
            valueField: "id"
            displayFields: ["title"]
          - label: Challenge
            name: challenge
            widget: "relation"
            collection: "challenge"
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
            required: false          
            hint: "Only if clearly related to a Challenge in context of this role"
          - label: Role
            name: role
            widget: "relation"
            collection: "role"
            searchFields: ["id", "title"]
            valueField: "id"
            displayFields: ["title"]                
          - label: Professions
            name: professions            
            widget: list
            required: false  
            hint: "Professional background in context of this role"
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: Profession, name: profession, widget: string}  
          - label: Talk Titles
            name: talkTitles            
            widget: list
            required: false  
            hint: "If a speaker: What is the title of the Talk?"
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: Talk Title, name: talkTitle, widget: string}  
          - label: Timeslots
            name: timeslots
            widget: list
            required: false  
            hint: "Time of availability at Hackathon"
            fields:                
                - {label: "From", name: "from", widget: "datetime", format: "X", required: false}
                - {label: "To", name: "to", widget: "datetime", format: "X", required: false}
          - label: Descriptions
            name: descriptions            
            widget: list
            required: false  
            hint: "Usage: Speaker details"
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: Description, name: description, widget: text}              
  - name: "role"
    label: "Role"
    folder: "content/roles"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{title}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Title", name: "title", widget: "string"}
  - name: "partner"
    label: "Partner"
    folder: "content/partners"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{nameInternal}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "(internal) Name", name: "nameInternal", widget: "string", hint: "Used in Admin UI only"}
      - label: Names
        name: names
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Name, name: name, widget: string}  
      - label: Logo
        name: logo
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 256000 
      - label: Roles
        name: roles
        widget: list
        fields:                  
          - label: Hackathon
            name: hackathon
            widget: "relation"
            collection: "hackathon"
            searchFields: ["id", "title"]
            valueField: "id"
            displayFields: ["title"]
          - label: Challenge
            name: challenge
            widget: "relation"
            collection: "challenge"
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
            required: false     
          - {label: "Sponsor", name: "isSponsor", widget: "boolean", default: false}
          - label: Subtitles
            name: subtitles
            widget: list
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: subtitle, name: subtitle, widget: string}    
  - name: "timetable"
    label: "Timetable"
    folder: "content/timetables"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{title}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Title", name: "title", widget: "string"}      
      - label: Hackathon
        name: hackathon
        widget: "relation"
        collection: "hackathon"
        searchFields: ["id", "title"]
        valueField: "id"
        displayFields: ["title"]
      - {label: "Date", name: "date", widget: "datetime", format: "X", timeFormat: false}
      - label: Slots
        name: slots
        widget: list
        fields:          
          - label: Titles
            name: titles
            widget: list
            hint: "Optional, is overwritten if Speaker is selected"
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: Title, name: title, widget: string}              
          - {label: "From", name: "from", widget: "datetime", format: "X"}
          - label: Image
            name: image
            widget: "image"
            required: false
            media_library:
              config:
                max_file_size: 256000 
          - label: External Link
            name: linkExternal
            widget: "relation"
            collection: "link"
            required: false
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
          - label: Speaker
            name: speaker
            widget: "relation"
            collection: "person"
            required: false
            searchFields: ["id", "name"]
            valueField: "id"
            displayFields: ["name"]
          - label: Descriptions
            name: descriptions
            widget: list
            fields:
              - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
              - {label: Description, name: description, widget: text}
  - name: "faq"
    label: "FAQs"
    folder: "content/faqs"
    format: json
    create: true
    slug: "{{slug}}"
    identifier_field: id
    summary: "{{name}} ({{id}})"
    fields:
      - {label: "ID", name: "id", widget: "uuid", hint: "A unique string to ensure correct relations and queries"}
      - {label: "Name", name: "name", widget: "string", hint: "Used in Admin UI only"}
      - label: Question
        name: question
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Question, name: question, widget: string}
      - label: Answer
        name: answer
        widget: list
        fields:
          - {label: Language, name: language, widget: select, options: ["DE", "EN"]}
          - {label: Answer, name: answer, widget: markdown}
